spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vasimvahabov/config-repo.git
          default-label: main
          searchPaths: "{application}"
          timeout: 15
          clone-on-start: true
          force-pull: true

server:
  port: 6464
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 50